[package]
name = "rwa-oracle"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
odra = "2.7.2"
odra-casper-livenet-env = { version = "2.7.2", optional = true }

[dev-dependencies]
odra-test = "2.7.2"

[build-dependencies]
odra-build = "2.7.2"

[features]
default = []
livenet = ["odra-casper-livenet-env"]

[[bin]]
name = "rwa_oracle_build_contract"
path = "src/bin/rwa_oracle_build_contract.rs"
test = false

[[bin]]
name = "deploy"
path = "src/bin/deploy.rs"
required-features = ["livenet"]
test = false

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(odra_module, values("RwaOracle"))'] }
